spring:
  datasource:
    url: jdbc:postgresql://task_postgres:5432/taskdb
    username: username
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: 'classpath:db/master.xml'